/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package matrix;

/**
 *
 * @author MKS
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderBG = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        Order3RB = new javax.swing.JRadioButton();
        Order2RB = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        AppsRB = new javax.swing.JRadioButton();
        AboutRB = new javax.swing.JRadioButton();
        Img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matrices");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 52)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html> <body>   <center> Matrices</center> </body> </html>");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 270, -1));

        Order3RB.setBackground(new java.awt.Color(18, 122, 93));
        orderBG.add(Order3RB);
        Order3RB.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Order3RB.setForeground(new java.awt.Color(255, 255, 255));
        Order3RB.setText("3X3 order");
        Order3RB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Order3RBItemStateChanged(evt);
            }
        });
        getContentPane().add(Order3RB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        Order2RB.setBackground(new java.awt.Color(19, 124, 93));
        orderBG.add(Order2RB);
        Order2RB.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        Order2RB.setForeground(new java.awt.Color(255, 255, 255));
        Order2RB.setText("2X2 order");
        Order2RB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Order2RBItemStateChanged(evt);
            }
        });
        getContentPane().add(Order2RB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html> <body><center>*&nbsp Select the order of the matrice</center> </body> </html>");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 360, -1));

        AppsRB.setBackground(new java.awt.Color(22, 130, 99));
        buttonGroup1.add(AppsRB);
        AppsRB.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        AppsRB.setForeground(new java.awt.Color(255, 255, 255));
        AppsRB.setText("<html> <body><center>Its Application</center> </body> </html>");
        AppsRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AppsRBItemStateChanged(evt);
            }
        });
        getContentPane().add(AppsRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        AboutRB.setBackground(new java.awt.Color(22, 130, 99));
        buttonGroup1.add(AboutRB);
        AboutRB.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        AboutRB.setForeground(new java.awt.Color(255, 255, 255));
        AboutRB.setText("<html> <body><center >What is matrix ?</center> </body> </html>");
        AboutRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AboutRBItemStateChanged(evt);
            }
        });
        AboutRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutRBActionPerformed(evt);
            }
        });
        getContentPane().add(AboutRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matrix/green-blank-blackboard.jpg"))); // NOI18N
        getContentPane().add(Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Order2RBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Order2RBItemStateChanged
        if(Order2RB.isSelected()==true){
            Matrices_2x2 two = new Matrices_2x2();
          two.setVisible(true);
        }
    }//GEN-LAST:event_Order2RBItemStateChanged

    private void Order3RBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Order3RBItemStateChanged
     if(Order3RB.isSelected()==true){
            Matrices_3X3 two = new Matrices_3X3();
          two.setVisible(true);
        } 
    }//GEN-LAST:event_Order3RBItemStateChanged

    private void AboutRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutRBActionPerformed

    private void AboutRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AboutRBItemStateChanged
 if(AboutRB.isSelected()==true){
            About A = new About();
          A.setVisible(true);
        }
    }//GEN-LAST:event_AboutRBItemStateChanged

    private void AppsRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AppsRBItemStateChanged
  if(AppsRB.isSelected()==true){
            Apps C = new Apps();
          C.setVisible(true);
        }
    }//GEN-LAST:event_AppsRBItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AboutRB;
    private javax.swing.JRadioButton AppsRB;
    private javax.swing.JLabel Img;
    private javax.swing.JRadioButton Order2RB;
    private javax.swing.JRadioButton Order3RB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.ButtonGroup orderBG;
    // End of variables declaration//GEN-END:variables
}
