/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package matrix;

import javax.swing.JOptionPane;
  
/**
 *
 * @author MKS
 */
public class Matrices_2x2 extends javax.swing.JFrame {

    /**
     * Creates new form Matrices_2x2
     */
    public Matrices_2x2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        a2 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        c2 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        SignTF = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        e2 = new javax.swing.JTextField();
        e1 = new javax.swing.JTextField();
        f1 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        AddBTN = new javax.swing.JButton();
        SubtractBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        multiplyBTN = new javax.swing.JButton();
        ClearBTN = new javax.swing.JButton();
        ReurnBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matrices(2x2 order)");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 30, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 140));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 30, 10));

        a2.setBackground(new java.awt.Color(22, 132, 101));
        a2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a2.setForeground(new java.awt.Color(255, 255, 255));
        a2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        a2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                a2FocusLost(evt);
            }
        });
        a2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a2KeyTyped(evt);
            }
        });
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 65, 30));

        a1.setBackground(new java.awt.Color(22, 132, 101));
        a1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 255, 255));
        a1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        a1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                a1FocusLost(evt);
            }
        });
        a1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a1KeyTyped(evt);
            }
        });
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 65, 30));

        b1.setBackground(new java.awt.Color(22, 132, 101));
        b1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        b1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                b1FocusLost(evt);
            }
        });
        b1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b1KeyTyped(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 65, 30));

        b2.setBackground(new java.awt.Color(22, 132, 101));
        b2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        b2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                b2FocusLost(evt);
            }
        });
        b2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b2KeyTyped(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 65, 30));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 10, 140));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 30, 10));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 30, 10));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("=");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 60, 40));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 30, 10));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, 140));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 30, 10));

        c2.setBackground(new java.awt.Color(17, 117, 87));
        c2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        c2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c2FocusLost(evt);
            }
        });
        c2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c2KeyTyped(evt);
            }
        });
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 65, 30));

        c1.setBackground(new java.awt.Color(17, 117, 87));
        c1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c1FocusLost(evt);
            }
        });
        c1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c1KeyTyped(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 65, 30));

        d1.setBackground(new java.awt.Color(17, 117, 87));
        d1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        d1.setForeground(new java.awt.Color(255, 255, 255));
        d1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        d1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                d1FocusLost(evt);
            }
        });
        d1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                d1KeyTyped(evt);
            }
        });
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 65, 30));

        d2.setBackground(new java.awt.Color(17, 117, 87));
        d2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        d2.setForeground(new java.awt.Color(255, 255, 255));
        d2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        d2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                d2FocusLost(evt);
            }
        });
        d2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                d2KeyTyped(evt);
            }
        });
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 65, 30));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 10, 140));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 30, 10));
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 30, 10));

        SignTF.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SignTF.setForeground(new java.awt.Color(255, 255, 255));
        SignTF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(SignTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 60, 40));
        getContentPane().add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 30, 10));

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, -1, 140));
        getContentPane().add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 390, 30, 10));

        e2.setEditable(false);
        e2.setBackground(new java.awt.Color(14, 104, 76));
        e2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        e2.setForeground(new java.awt.Color(255, 255, 255));
        e2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 65, 30));

        e1.setEditable(false);
        e1.setBackground(new java.awt.Color(14, 104, 76));
        e1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        e1.setForeground(new java.awt.Color(255, 255, 255));
        e1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 65, 30));

        f1.setEditable(false);
        f1.setBackground(new java.awt.Color(14, 104, 76));
        f1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        f1.setForeground(new java.awt.Color(255, 255, 255));
        f1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 65, 30));

        f2.setEditable(false);
        f2.setBackground(new java.awt.Color(14, 104, 76));
        f2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        f2.setForeground(new java.awt.Color(255, 255, 255));
        f2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 65, 30));

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 10, 140));
        getContentPane().add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 30, 10));
        getContentPane().add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 30, 10));

        AddBTN.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        AddBTN.setForeground(new java.awt.Color(51, 0, 255));
        AddBTN.setText("+");
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTNActionPerformed(evt);
            }
        });
        getContentPane().add(AddBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 60, 40));

        SubtractBTN.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        SubtractBTN.setForeground(new java.awt.Color(255, 153, 0));
        SubtractBTN.setText("-");
        SubtractBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SubtractBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 60, 40));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html> <body>   <center> Matrices</center> </body> </html>");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 270, -1));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("(2X2 order)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 90, -1));

        multiplyBTN.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        multiplyBTN.setForeground(new java.awt.Color(102, 0, 102));
        multiplyBTN.setText("*");
        multiplyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyBTNActionPerformed(evt);
            }
        });
        getContentPane().add(multiplyBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 60, 40));

        ClearBTN.setBackground(new java.awt.Color(6, 51, 40));
        ClearBTN.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        ClearBTN.setForeground(new java.awt.Color(153, 0, 0));
        ClearBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matrix/su.jpg"))); // NOI18N
        ClearBTN.setBorder(null);
        ClearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ClearBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, 150, 50));

        ReurnBTN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ReurnBTN.setForeground(new java.awt.Color(153, 0, 0));
        ReurnBTN.setText("<<  Back");
        ReurnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReurnBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ReurnBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, 30));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html>\n<body>\nMath is the science which uses easy words for hard ideas.\n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n- Edward Kasner\n\n</body>\n</html>");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 940, 50));

        Img.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Img.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matrix/green-blank-blackboard.jpg"))); // NOI18N
        getContentPane().add(Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1029, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTNActionPerformed
      double A1 = Double.parseDouble(a1.getText());
      double A2 = Double.parseDouble(a2.getText());
      double B1 = Double.parseDouble(b1.getText());
      double B2 = Double.parseDouble(b2.getText());
       
      double C1 = Double.parseDouble(c1.getText());
      double C2 = Double.parseDouble(c2.getText());
      double D1 = Double.parseDouble(d1.getText());
      double D2 = Double.parseDouble(d2.getText());
        
      double E1 = A1+C1;
      double E2 = A2+C2;
      double F1 = B1+D1;
      double F2 = B2+D2;
      
      e1.setText(""+E1);
      e2.setText(""+E2);
      f1.setText(""+F1);
      f2.setText(""+F2);
      
      SignTF.setText("+");
        
    }//GEN-LAST:event_AddBTNActionPerformed

    private void SubtractBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractBTNActionPerformed
     double A1 = Double.parseDouble(a1.getText());
      double A2 = Double.parseDouble(a2.getText());
      double B1 = Double.parseDouble(b1.getText());
      double B2 = Double.parseDouble(b2.getText());
       
      double C1 = Double.parseDouble(c1.getText());
      double C2 = Double.parseDouble(c2.getText());
      double D1 = Double.parseDouble(d1.getText());
      double D2 = Double.parseDouble(d2.getText());
        
      
      
      double E1 = A1-C1;
      double E2 = A2-C2;
      double F1 = B1-D1;
      double F2 = B2-D2;
      
      e1.setText(""+E1);
      e2.setText(""+E2);
      f1.setText(""+F1);
      f2.setText(""+F2);
      
      SignTF.setText("-");
        
        
        
    }//GEN-LAST:event_SubtractBTNActionPerformed

    private void multiplyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyBTNActionPerformed
      double A1 = Double.parseDouble(a1.getText());
      double A2 = Double.parseDouble(a2.getText());
      double B1 = Double.parseDouble(b1.getText());
      double B2 = Double.parseDouble(b2.getText());
       
      double C1 = Double.parseDouble(c1.getText());
      double C2 = Double.parseDouble(c2.getText());
      double D1 = Double.parseDouble(d1.getText());
      double D2 = Double.parseDouble(d2.getText());
        
      
      
      double E1 = (A1*C1)+(A2*D1);
      double E2 = (A1*C2)+(A2*D2);
      double F1 = (B1*C1)+(B2*D1);
      double F2 = (B1*C2)+(B2*D2);
      
      e1.setText(""+E1);
      e2.setText(""+E2);
      f1.setText(""+F1);
      f2.setText(""+F2);
      
      SignTF.setText("*");
        
        
    }//GEN-LAST:event_multiplyBTNActionPerformed

    private void a1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a1KeyTyped
char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_a1KeyTyped

    private void a1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a1FocusLost
    double val = Double.parseDouble(a1.getText());
   if((val>=1000)||(val<=-1000))
   {
       JOptionPane.showMessageDialog(null,"Digit should be the range of -999 to 999. ");
       ClearBTN.doClick();
      
   }
    }//GEN-LAST:event_a1FocusLost

    private void a2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a2FocusLost
      double val = Double.parseDouble(a2.getText());
   if((val>=1000)||(val<=-1000))
   {
       JOptionPane.showMessageDialog(null,"Digit should be the range of -999 to 999. ");
       ClearBTN.doClick();
      
   }
    }//GEN-LAST:event_a2FocusLost

    private void b1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b1FocusLost
    double val = Double.parseDouble(b1.getText());
   if((val>=1000)||(val<=-1000))
   {
       JOptionPane.showMessageDialog(null,"Digit should be the range of -999 to 999. ");
       ClearBTN.doClick();
      
   }
    }//GEN-LAST:event_b1FocusLost

    private void b2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b2FocusLost
        double val = Double.parseDouble(b2.getText());
   if((val>=1000)||(val<=-1000))
   {
       JOptionPane.showMessageDialog(null,"Digit should be the range of -999 to 999. ");
       ClearBTN.doClick();
      
   }
    }//GEN-LAST:event_b2FocusLost

    private void c1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c1FocusLost
        double val = Double.parseDouble(c1.getText());
   if((val>=1000)||(val<=-1000))
   {
       JOptionPane.showMessageDialog(null,"Digit should be the range of -999 to 999. ");
       ClearBTN.doClick();
      
   }
    }//GEN-LAST:event_c1FocusLost

    private void c2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c2FocusLost
        double val = Double.parseDouble(c2.getText());
   if((val>=1000)||(val<=-1000))
   {
       JOptionPane.showMessageDialog(null,"Digit should be the range of -999 to 999. ");
       ClearBTN.doClick();
      
   }
    }//GEN-LAST:event_c2FocusLost

    private void d1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_d1FocusLost
         double val = Double.parseDouble(d1.getText());
   if((val>=1000)||(val<=-1000))
   {
       JOptionPane.showMessageDialog(null,"Digit should be the range of -999 to 999. ");
       ClearBTN.doClick();
      
   }
    }//GEN-LAST:event_d1FocusLost

    private void d2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_d2FocusLost
       double val = Double.parseDouble(d2.getText());
   if((val>=1000)||(val<=-1000))
   {
       JOptionPane.showMessageDialog(null,"Digit should be the range of -999 to 999. ");
       ClearBTN.doClick();
      
   }
    }//GEN-LAST:event_d2FocusLost

    private void ClearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTNActionPerformed
  a1.setText("");
    a2.setText("");
    b1.setText("");
    b2.setText("");
    c1.setText("");
    c2.setText("");
    d1.setText("");
    d2.setText("");
    e1.setText("");
    e2.setText("");
    f1.setText("");
    f2.setText("");
    SignTF.setText("");
    }//GEN-LAST:event_ClearBTNActionPerformed

    private void ReurnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReurnBTNActionPerformed
MainMenu main = new MainMenu();
main.setVisible(true);
this.setVisible(false);
        
    }//GEN-LAST:event_ReurnBTNActionPerformed

    private void a2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a2KeyTyped
   char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_a2KeyTyped

    private void b1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b1KeyTyped
    char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_b1KeyTyped

    private void b2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b2KeyTyped
   char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_b2KeyTyped

    private void c1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c1KeyTyped
     char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_c1KeyTyped

    private void c2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c2KeyTyped
    char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_c2KeyTyped

    private void d1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_d1KeyTyped
    char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_d1KeyTyped

    private void d2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_d2KeyTyped
   char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_d2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matrices_2x2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matrices_2x2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matrices_2x2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matrices_2x2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matrices_2x2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.JButton ClearBTN;
    private javax.swing.JLabel Img;
    private javax.swing.JButton ReurnBTN;
    private javax.swing.JLabel SignTF;
    private javax.swing.JButton SubtractBTN;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton multiplyBTN;
    // End of variables declaration//GEN-END:variables
}
