/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package matrix;

import javax.swing.JOptionPane;

/**
 *
 * @author MKS
 */
public class Matrices_3X3 extends javax.swing.JFrame {

    /**
     * Creates new form Matrices_3X3
     */
    public Matrices_3X3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        multiplyBTN = new javax.swing.JButton();
        c1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        SignTF = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        SubtractBTN = new javax.swing.JButton();
        AddBTN = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        ClearBTN = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        a1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        d3 = new javax.swing.JTextField();
        e1 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        f2 = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        e2 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        f1 = new javax.swing.JTextField();
        e3 = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        d2 = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        g3 = new javax.swing.JTextField();
        h1 = new javax.swing.JTextField();
        g1 = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        i2 = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        jSeparator29 = new javax.swing.JSeparator();
        h2 = new javax.swing.JTextField();
        i3 = new javax.swing.JTextField();
        i1 = new javax.swing.JTextField();
        h3 = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();
        g2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ReurnBTN = new javax.swing.JButton();
        Img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matrices(3x3 order)");
        setMinimumSize(new java.awt.Dimension(1100, 810));
        setPreferredSize(new java.awt.Dimension(1091, 780));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        multiplyBTN.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        multiplyBTN.setForeground(new java.awt.Color(102, 0, 102));
        multiplyBTN.setText("*");
        multiplyBTN.setPreferredSize(new java.awt.Dimension(91, 91));
        multiplyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyBTNActionPerformed(evt);
            }
        });
        getContentPane().add(multiplyBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 60, 50));

        c1.setBackground(new java.awt.Color(22, 127, 96));
        c1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c1FocusLost(evt);
            }
        });
        c1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c1KeyTyped(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 65, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 30, 10));

        SignTF.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SignTF.setForeground(new java.awt.Color(255, 255, 255));
        SignTF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(SignTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 60, 40));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 30, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 30, 10));

        SubtractBTN.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        SubtractBTN.setForeground(new java.awt.Color(255, 153, 0));
        SubtractBTN.setText("-");
        SubtractBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SubtractBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 60, 50));

        AddBTN.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        AddBTN.setForeground(new java.awt.Color(51, 0, 255));
        AddBTN.setText("+");
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTNActionPerformed(evt);
            }
        });
        getContentPane().add(AddBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 60, 50));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 30, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 10, 180));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("(3X3 order)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 90, -1));

        ClearBTN.setBackground(new java.awt.Color(6, 51, 40));
        ClearBTN.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        ClearBTN.setForeground(new java.awt.Color(153, 0, 0));
        ClearBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matrix/su.jpg"))); // NOI18N
        ClearBTN.setBorder(null);
        ClearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ClearBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, 150, 50));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 10, 180));

        a1.setBackground(new java.awt.Color(22, 132, 101));
        a1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 255, 255));
        a1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        a1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                a1FocusLost(evt);
            }
        });
        a1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a1KeyTyped(evt);
            }
        });
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 65, 30));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html> <body>   <center> Matrices</center> </body> </html>");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 270, -1));

        a2.setBackground(new java.awt.Color(22, 132, 101));
        a2.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        a2.setForeground(new java.awt.Color(255, 255, 255));
        a2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        a2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                a2FocusLost(evt);
            }
        });
        a2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a2KeyTyped(evt);
            }
        });
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 65, 30));

        a3.setBackground(new java.awt.Color(22, 132, 101));
        a3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        a3.setForeground(new java.awt.Color(255, 255, 255));
        a3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        a3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                a3FocusLost(evt);
            }
        });
        a3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a3KeyTyped(evt);
            }
        });
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 65, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("=");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 60, 40));

        b1.setBackground(new java.awt.Color(21, 132, 100));
        b1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        b1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                b1FocusLost(evt);
            }
        });
        b1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b1KeyTyped(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 65, 30));

        b3.setBackground(new java.awt.Color(21, 132, 100));
        b3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        b3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                b3FocusLost(evt);
            }
        });
        b3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b3KeyTyped(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 65, 30));

        c3.setBackground(new java.awt.Color(22, 127, 96));
        c3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        c3.setForeground(new java.awt.Color(255, 255, 255));
        c3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        c3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c3FocusLost(evt);
            }
        });
        c3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c3KeyTyped(evt);
            }
        });
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 65, 30));

        b2.setBackground(new java.awt.Color(21, 132, 100));
        b2.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        b2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                b2FocusLost(evt);
            }
        });
        b2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b2KeyTyped(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 65, 30));

        c2.setBackground(new java.awt.Color(22, 127, 96));
        c2.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        c2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c2FocusLost(evt);
            }
        });
        c2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c2KeyTyped(evt);
            }
        });
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 65, 30));

        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 10, 180));

        d3.setBackground(new java.awt.Color(15, 112, 81));
        d3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        d3.setForeground(new java.awt.Color(255, 255, 255));
        d3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        d3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                d3FocusLost(evt);
            }
        });
        d3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                d3KeyTyped(evt);
            }
        });
        getContentPane().add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 65, 30));

        e1.setBackground(new java.awt.Color(16, 119, 90));
        e1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        e1.setForeground(new java.awt.Color(255, 255, 255));
        e1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        e1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                e1FocusLost(evt);
            }
        });
        e1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e1KeyTyped(evt);
            }
        });
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 65, 30));

        d1.setBackground(new java.awt.Color(19, 119, 89));
        d1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        d1.setForeground(new java.awt.Color(255, 255, 255));
        d1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        d1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                d1FocusLost(evt);
            }
        });
        d1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                d1KeyTyped(evt);
            }
        });
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 65, 30));
        getContentPane().add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 30, 10));
        getContentPane().add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 30, 10));

        f2.setBackground(new java.awt.Color(22, 112, 86));
        f2.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        f2.setForeground(new java.awt.Color(255, 255, 255));
        f2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        f2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                f2FocusLost(evt);
            }
        });
        f2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                f2KeyTyped(evt);
            }
        });
        getContentPane().add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 65, 30));
        getContentPane().add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 30, 10));

        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 10, 180));

        e2.setBackground(new java.awt.Color(12, 117, 87));
        e2.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        e2.setForeground(new java.awt.Color(255, 255, 255));
        e2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        e2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                e2FocusLost(evt);
            }
        });
        e2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e2KeyTyped(evt);
            }
        });
        getContentPane().add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 65, 30));

        f3.setBackground(new java.awt.Color(22, 107, 78));
        f3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        f3.setForeground(new java.awt.Color(255, 255, 255));
        f3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        f3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                f3FocusLost(evt);
            }
        });
        f3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                f3KeyTyped(evt);
            }
        });
        getContentPane().add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 65, 30));

        f1.setBackground(new java.awt.Color(24, 117, 87));
        f1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        f1.setForeground(new java.awt.Color(255, 255, 255));
        f1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        f1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                f1FocusLost(evt);
            }
        });
        f1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                f1KeyTyped(evt);
            }
        });
        getContentPane().add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 65, 30));

        e3.setBackground(new java.awt.Color(23, 109, 80));
        e3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        e3.setForeground(new java.awt.Color(255, 255, 255));
        e3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        e3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                e3FocusLost(evt);
            }
        });
        e3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e3KeyTyped(evt);
            }
        });
        getContentPane().add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 65, 30));
        getContentPane().add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 30, 10));

        d2.setBackground(new java.awt.Color(18, 114, 85));
        d2.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        d2.setForeground(new java.awt.Color(255, 255, 255));
        d2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        d2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                d2FocusLost(evt);
            }
        });
        d2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                d2KeyTyped(evt);
            }
        });
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 65, 30));

        jSeparator25.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 10, 180));

        g3.setEditable(false);
        g3.setBackground(new java.awt.Color(13, 96, 70));
        g3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        g3.setForeground(new java.awt.Color(255, 255, 255));
        g3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(g3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 260, 65, 30));

        h1.setEditable(false);
        h1.setBackground(new java.awt.Color(8, 107, 75));
        h1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        h1.setForeground(new java.awt.Color(255, 255, 255));
        h1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 65, 30));

        g1.setEditable(false);
        g1.setBackground(new java.awt.Color(15, 104, 76));
        g1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        g1.setForeground(new java.awt.Color(255, 255, 255));
        g1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        g1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                g1FocusLost(evt);
            }
        });
        g1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                g1KeyTyped(evt);
            }
        });
        getContentPane().add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 65, 30));
        getContentPane().add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 420, 30, 10));
        getContentPane().add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 30, 10));

        i2.setEditable(false);
        i2.setBackground(new java.awt.Color(10, 104, 74));
        i2.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        i2.setForeground(new java.awt.Color(255, 255, 255));
        i2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(i2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 360, 65, 30));
        getContentPane().add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 240, 30, 10));

        jSeparator29.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 240, 10, 180));

        h2.setEditable(false);
        h2.setBackground(new java.awt.Color(7, 107, 75));
        h2.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        h2.setForeground(new java.awt.Color(255, 255, 255));
        h2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(h2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, 65, 30));

        i3.setEditable(false);
        i3.setBackground(new java.awt.Color(19, 96, 73));
        i3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        i3.setForeground(new java.awt.Color(255, 255, 255));
        i3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(i3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 65, 30));

        i1.setEditable(false);
        i1.setBackground(new java.awt.Color(10, 107, 76));
        i1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        i1.setForeground(new java.awt.Color(255, 255, 255));
        i1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(i1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 65, 30));

        h3.setEditable(false);
        h3.setBackground(new java.awt.Color(7, 96, 68));
        h3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        h3.setForeground(new java.awt.Color(255, 255, 255));
        h3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(h3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 310, 65, 30));
        getContentPane().add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 30, 10));

        g2.setEditable(false);
        g2.setBackground(new java.awt.Color(14, 104, 76));
        g2.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        g2.setForeground(new java.awt.Color(255, 255, 255));
        g2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 65, 30));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html>\n<body>\n\nEducation is what remains after one has forgotten\n everything he learned in school. \n<br>\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n~Albert Einstein\n</body>\n</html>");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 940, 60));

        ReurnBTN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ReurnBTN.setForeground(new java.awt.Color(153, 0, 0));
        ReurnBTN.setText("<<  Back");
        ReurnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReurnBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ReurnBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, -1, 30));

        Img.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matrix/green.jpg"))); // NOI18N
        Img.setPreferredSize(new java.awt.Dimension(1091, 780));
        getContentPane().add(Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void multiplyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyBTNActionPerformed
double A1 = Double.parseDouble(a1.getText());
      double A2 = Double.parseDouble(a2.getText());
      double A3 = Double.parseDouble(a3.getText());
      double B1 = Double.parseDouble(b1.getText());
      double B2 = Double.parseDouble(b2.getText());
      double B3 = Double.parseDouble(b3.getText());
      double C1 = Double.parseDouble(c1.getText());
      double C2 = Double.parseDouble(c2.getText());
      double C3 = Double.parseDouble(c3.getText());
      
      double D1 = Double.parseDouble(d1.getText());
      double D2 = Double.parseDouble(d2.getText());       
      double D3 = Double.parseDouble(d3.getText());       
      double E1 = Double.parseDouble(e1.getText());
      double E2 = Double.parseDouble(e2.getText());       
      double E3 = Double.parseDouble(e3.getText());       
      double F1 = Double.parseDouble(f1.getText());
      double F2 = Double.parseDouble(f2.getText());       
      double F3 = Double.parseDouble(f3.getText());      
      
      double G1 = (A1*D1)+(A2*E1)+(A3*F1);
      double G2 = (A1*D2)+(A2*E2)+(A3*F2);
      double G3 = (A1*D3)+(A2*E3)+(A3*F3);
      double H1 = (B1*D1)+(B2*E1)+(B3*F1);
      double H2 = (B1*D2)+(B2*E2)+(B3*F2);
      double H3 = (B1*D3)+(B2*E3)+(B3*F3);
      double I1 = (C1*D1)+(C2*E1)+(C3*F1);
      double I2 = (C1*D2)+(C2*E2)+(C3*F2);
      double I3 = (C1*D3)+(C2*E3)+(C3*F3);;
      
      g1.setText(""+G1);
      g2.setText(""+G2);
      g3.setText(""+G3);
      h1.setText(""+H1);
      h2.setText(""+H2);
      h3.setText(""+H3);
      i1.setText(""+I1);
      i2.setText(""+I2);
      i3.setText(""+I3);
      
      SignTF.setText("*");      

    }//GEN-LAST:event_multiplyBTNActionPerformed

    private void SubtractBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractBTNActionPerformed
      double A1 = Double.parseDouble(a1.getText());
      double A2 = Double.parseDouble(a2.getText());
      double A3 = Double.parseDouble(a3.getText());
      double B1 = Double.parseDouble(b1.getText());
      double B2 = Double.parseDouble(b2.getText());
      double B3 = Double.parseDouble(b3.getText());
      double C1 = Double.parseDouble(c1.getText());
      double C2 = Double.parseDouble(c2.getText());
      double C3 = Double.parseDouble(c3.getText());
      
      double D1 = Double.parseDouble(d1.getText());
      double D2 = Double.parseDouble(d2.getText());       
      double D3 = Double.parseDouble(d3.getText());       
      double E1 = Double.parseDouble(e1.getText());
      double E2 = Double.parseDouble(e2.getText());       
      double E3 = Double.parseDouble(e3.getText());       
      double F1 = Double.parseDouble(f1.getText());
      double F2 = Double.parseDouble(f2.getText());       
      double F3 = Double.parseDouble(f3.getText());      
      
      double G1 = A1-D1;
      double G2 = A2-D2;
      double G3 = A3-D3;
      double H1 = B1-E1;
      double H2 = B2-E2;
      double H3 = B3-E3;
      double I1 = C1-F1;
      double I2 = C2-F2;
      double I3 = C3-F3;
      
      g1.setText(""+G1);
      g2.setText(""+G2);
      g3.setText(""+G3);
      h1.setText(""+H1);
      h2.setText(""+H2);
      h3.setText(""+H3);
      i1.setText(""+I1);
      i2.setText(""+I2);
      i3.setText(""+I3);
      
      SignTF.setText("-");       

    }//GEN-LAST:event_SubtractBTNActionPerformed

    private void AddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTNActionPerformed
      double A1 = Double.parseDouble(a1.getText());
      double A2 = Double.parseDouble(a2.getText());
      double A3 = Double.parseDouble(a3.getText());
      double B1 = Double.parseDouble(b1.getText());
      double B2 = Double.parseDouble(b2.getText());
      double B3 = Double.parseDouble(b3.getText());
      double C1 = Double.parseDouble(c1.getText());
      double C2 = Double.parseDouble(c2.getText());
      double C3 = Double.parseDouble(c3.getText());
      
      double D1 = Double.parseDouble(d1.getText());
      double D2 = Double.parseDouble(d2.getText());       
      double D3 = Double.parseDouble(d3.getText());       
      double E1 = Double.parseDouble(e1.getText());
      double E2 = Double.parseDouble(e2.getText());       
      double E3 = Double.parseDouble(e3.getText());       
      double F1 = Double.parseDouble(f1.getText());
      double F2 = Double.parseDouble(f2.getText());       
      double F3 = Double.parseDouble(f3.getText());      
      
      double G1 = A1+D1;
      double G2 = A2+D2;
      double G3 = A3+D3;
      double H1 = B1+E1;
      double H2 = B2+E2;
      double H3 = B3+E3;
      double I1 = C1+F1;
      double I2 = C2+F2;
      double I3 = C3+F3;
      
      g1.setText(""+G1);
      g2.setText(""+G2);
      g3.setText(""+G3);
      h1.setText(""+H1);
      h2.setText(""+H2);
      h3.setText(""+H3);
      i1.setText(""+I1);
      i2.setText(""+I2);
      i3.setText(""+I3);
      
      SignTF.setText("+");
     
    }//GEN-LAST:event_AddBTNActionPerformed

    private void ClearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTNActionPerformed
      a1.setText("");
      a2.setText("");
      a3.setText("");
      b1.setText("");
      b2.setText("");
      b3.setText("");
      c1.setText("");
      c2.setText("");
      c3.setText("");
      d1.setText("");
      d2.setText("");
      d3.setText("");
      e1.setText("");
      e2.setText("");
      e3.setText("");
      f1.setText("");
      f2.setText("");
      f3.setText("");
      g1.setText("");
      g2.setText("");
      g3.setText("");
      h1.setText("");
      h2.setText("");
      h3.setText("");
      i1.setText("");
      i2.setText("");
      i3.setText("");
      SignTF.setText("");
    }//GEN-LAST:event_ClearBTNActionPerformed

    private void a1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a1FocusLost
    double val = Double.parseDouble(a1.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_a1FocusLost

    private void a1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a1KeyTyped
char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_a1KeyTyped

    private void d1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_d1FocusLost
        double val = Double.parseDouble(d1.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_d1FocusLost

    private void d1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_d1KeyTyped
   char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_d1KeyTyped

    private void g1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_g1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_g1FocusLost

    private void g1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_g1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_g1KeyTyped

    private void a2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a2FocusLost
  double val = Double.parseDouble(a2.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_a2FocusLost

    private void a3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a3FocusLost
      double val = Double.parseDouble(a3.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_a3FocusLost

    private void b1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b1FocusLost
     double val = Double.parseDouble(b1.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_b1FocusLost

    private void b2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b2FocusLost
  double val = Double.parseDouble(b2.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_b2FocusLost

    private void b3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b3FocusLost
     double val = Double.parseDouble(b3.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_b3FocusLost

    private void c1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c1FocusLost
     double val = Double.parseDouble(c1.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_c1FocusLost

    private void c2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c2FocusLost
      double val = Double.parseDouble(c2.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_c2FocusLost

    private void c3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c3FocusLost
    double val = Double.parseDouble(c3.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_c3FocusLost

    private void d2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_d2FocusLost
     double val = Double.parseDouble(d2.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_d2FocusLost

    private void d3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_d3FocusLost
     double val = Double.parseDouble(d3.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_d3FocusLost

    private void e1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e1FocusLost
     double val = Double.parseDouble(e1.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_e1FocusLost

    private void e2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e2FocusLost
     double val = Double.parseDouble(e2.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_e2FocusLost

    private void e3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_e3FocusLost
      double val = Double.parseDouble(e3.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_e3FocusLost

    private void f1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f1FocusLost
      double val = Double.parseDouble(f1.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_f1FocusLost

    private void f2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f2FocusLost
      double val = Double.parseDouble(f2.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_f2FocusLost

    private void f3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f3FocusLost
     double val = Double.parseDouble(f3.getText());
   if((val>=100)||(val<=-100))
   {
       JOptionPane.showMessageDialog(null,"Please enter two digit no only. ");
       ClearBTN.doClick();
      
   }       
    }//GEN-LAST:event_f3FocusLost

    private void a2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a2KeyTyped
      char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_a2KeyTyped

    private void a3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a3KeyTyped
  char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_a3KeyTyped

    private void b1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b1KeyTyped
   char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_b1KeyTyped

    private void b2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b2KeyTyped
 char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_b2KeyTyped

    private void b3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b3KeyTyped
  char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_b3KeyTyped

    private void c1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c1KeyTyped
      char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_c1KeyTyped

    private void c2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c2KeyTyped
      char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_c2KeyTyped

    private void c3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c3KeyTyped
    char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_c3KeyTyped

    private void d2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_d2KeyTyped
    char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_d2KeyTyped

    private void d3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_d3KeyTyped
   char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_d3KeyTyped

    private void e1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e1KeyTyped
    char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_e1KeyTyped

    private void e2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e2KeyTyped
    char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_e2KeyTyped

    private void e3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e3KeyTyped
      char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_e3KeyTyped

    private void f1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f1KeyTyped
    char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_f1KeyTyped

    private void f2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f2KeyTyped
       char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_f2KeyTyped

    private void f3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f3KeyTyped
    char ch = evt.getKeyChar();
if((ch>='a'&& ch<='z')||(ch>='A'&& ch<='Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_f3KeyTyped

    private void ReurnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReurnBTNActionPerformed
        MainMenu main = new MainMenu();
        main.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_ReurnBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matrices_3X3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matrices_3X3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matrices_3X3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matrices_3X3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matrices_3X3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.JButton ClearBTN;
    private javax.swing.JLabel Img;
    private javax.swing.JButton ReurnBTN;
    private javax.swing.JLabel SignTF;
    private javax.swing.JButton SubtractBTN;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField d3;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField e3;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField g1;
    private javax.swing.JTextField g2;
    private javax.swing.JTextField g3;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField h2;
    private javax.swing.JTextField h3;
    private javax.swing.JTextField i1;
    private javax.swing.JTextField i2;
    private javax.swing.JTextField i3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton multiplyBTN;
    // End of variables declaration//GEN-END:variables
}
